import './sample.test';
import './unitTest/userTest';
import './users.test';
import './authentication.test'
import './sendEmail.test';
import './articles.test';
import './requestPassword.test';
import './resetPassword.test';
import './articleLike.test';
import './articleRating.test';
