import './articles.test';
import './bookmark.test';
import './comments.test';
import './followUser.test';
import './unfollowUser.test';
import './users.test'
import './articleLike.test';
import './articleRating.test';
import './report.test.js';
import './emailNotifications.test';
import './inAppNotifications.test';
